[nw-linux]
branch = "3rd-nw-linux"
commit = "e29efa98724a"
upstream = "upstream-linux-v5.17"

[optee-build]
branch = "3rd-optee-build"
commit = "f3760159a41e"

[realm-linux]
branch = "3rd-realm-linux"
commit = "8f6dc54433b3"
upstream = "upstream-linux-v5.17"

[tf-a-tests]
branch = "3rd-tf-a-tests"
commit = "1b20931058c3"
upstream = "upstream-tf-a-tests-v2.7"

[tf-a]
branch = "3rd-tf-a"
commit = "8ae28efc76a5"
upstream = "upstream-tf-a-v2.7"

[android-kernel]
branch = "3rd-android-kernel"
commit = "ad1f2eebadfe"

[gki-build]
branch = "3rd-gki-build"
commit = "5fe377f6a20b"
