[nw-linux]
branch = "3rd-nw-linux-230222"
commit = "604bc2c405be"
upstream = "upstream-linux-cca-rfc-v1"

[optee-build]
branch = "3rd-optee-build-230407"
commit = "13fe78ba976e"

[realm-linux]
branch = "3rd-realm-linux-230222"
commit = "c865d47546ee"
upstream = "upstream-linux-cca-rfc-v1"

[tf-a-tests]
branch = "3rd-tf-a-tests-230404"
commit = "1a00fff2b124"
upstream = "upstream-tftf-lts-v2.8"

[tf-a]
branch = "3rd-tf-a-230222"
commit = "33b4df9c1f77"
upstream = "upstream-tf-a-lts-v2.8"

[tf-rmm]
branch = "3rd-tf-rmm-230223"
commit = "708eb9d6ef16"

[android-kernel]
branch = "3rd-android-kernel-6.2"
commit = "b8859291c271"

[gki-build]
branch = "3rd-gki-build-230309"
commit = "ab86d3b2e485"

[kvmtool]
branch = "3rd-kvmtool-230227"
commit = "2e8fe7ff6124"
tag = "kvmtool-cca-rfc-v1"

[kvm-unit-tests]
branch = "3rd-kvm-unit-tests-230406"
commit = "05515ff54903"

[certifier]
branch = "3rd-certifier"
commit = "a65a397fc7a8"
tag = "upstream-certifier-230323"

[cca-rmm-acs]
branch = "3rd-cca-rmm-acs"
commit = "6ca7920ed262"
