[nw-linux]
branch = "3rd-linux-cca-rfc-v1"
commit = "dc921fa30f0c"
upstream = "upstream-linux-cca-rfc-v1"

[optee-build]
branch = "3rd-optee-build"
commit = "977f2f228bf7"

[realm-linux]
branch = "3rd-realm-linux"
commit = "8f6dc54433b3"
upstream = "upstream-linux-v5.17"

[tf-a-tests]
branch = "3rd-tf-a-tests"
commit = "f7b3be91ab95"
upstream = "upstream-tf-a-tests-v2.7"

[tf-a]
branch = "3rd-tf-a"
commit = "913627710563"
upstream = "upstream-tf-a-v2.7"

[tf-rmm]
branch = "3rd-tf-rmm-v0.2.0"
commit = "7d34f27fa9ff"

[android-kernel]
branch = "3rd-android-kernel"
commit = "ad1f2eebadfe"

[gki-build]
branch = "3rd-gki-build"
commit = "5fe377f6a20b"

[kvmtool]
branch = "3rd-kvmtool-cca-rfc-v1"
commit = "275981645b8b"
