[build]
target-dir = "target"

[target.aarch64-unknown-linux-gnu]
linker = "../assets/toolchain/aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc"
rustflags = [ "-C", "target-feature=+crt-static" ]
